export default {
    ADD_TO_CART: "ADD TO CART",
    REMOVE_FROM_CART: "REMOVE FROM CART",
    INCREASE_QUANTITY: "INCREASE QUANTITY",
    DECREASE_QUANTITY: "DECREASE QUANTITY",
    CLEAR_CART: "CLEAR CART"
}