export default {
    REQUEST_EXISTING_CATEGORIES: "REQUEST EXISTING CATEGORIES",
    SUCCESS_EXISTING_CATEGORIES: "SUCCESS EXISTING CATEGORIES",
    FAILURE_EXISTING_CATEGORIES: "FAILURE EXISTING CATEGORIES"
}