export default {
    REQUEST_PRODUCTS_BY_CATEGORY: "REQUEST PRODCUTS BY CATEGORY",
    SUCCESS_PRODUCTS_BY_CATEGORY: "SUCCESS PRODUCTS BY CATEGORY",
    FAILURE_PRODUCTS_BY_CATEGORY: "FAILURE PRODUCTS BY CATEGORY",
    REQUEST_ALL_PRODUCTS: "REQUEST ALL PRODUCTS",
    SUCCESS_ALL_PRODUCTS: "SUCCESS ALL PRODUCTS",
    FAILURE_ALL_PRODUCTS: "FAILURE ALL PRODUCTS",
    CHANGE_FILTER_VARIABLE: "CHANGE FILTER VARIABLE",
    CHANGE_META_DATA: "CHANGE META DATA",
    CHANGE_CURRENT_PRODUCT: "CHANGE CURRENT PRODUCT"
}